# Generated by Django 2.2.5 on 2019-10-03 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191003_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 19, 18, 40, 965954, tzinfo=utc)),
        ),
    ]
