# Generated by Django 2.2.5 on 2019-10-04 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20191004_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 18, 31, 18, 213842, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
    ]
