# Generated by Django 2.2.5 on 2019-10-17 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20191011_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 9, 1, 25, 328203, tzinfo=utc)),
        ),
    ]
