# Generated by Django 2.2.5 on 2019-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20191108_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
