# Generated by Django 2.2.5 on 2020-03-23 16:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profil_baner',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.photo_path),
        ),
    ]
