# Generated by Django 2.2.5 on 2020-03-24 10:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200323_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='profil_baner',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user_img',
            field=models.ImageField(upload_to=accounts.models.photo_path),
        ),
    ]
