# Generated by Django 2.2.5 on 2020-03-24 16:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200324_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.photo_path),
        ),
    ]
