# Generated by Django 2.2.5 on 2019-11-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IconCategory',
        ),
    ]
